header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: The Newton Developers

    license: |
      # SPDX-FileCopyrightText: Copyright (c) 2026 The Newton Developers
      # SPDX-License-Identifier: Apache-2.0

    pattern: |
      spdx-filecopyrighttext: copyright copyright \d{4}(?:-\d{4})? the newton developers
      spdx-license-identifier: apache-2\.0

  paths:
    - "**/*.py"

  paths-ignore:
    - "newton/_version.py"
    - "asv/benchmarks/**/__init__.py"
    - "newton/tests/thirdparty/__init__.py"

  comment: on-failure
