"""Experimental Digital Instron v2 elastic-foundation workflow."""

from .foundation import (
    FoundationFitResult,
    FoundationFitSample,
    FoundationGradientResult,
    FoundationMaterial,
    FoundationResult,
    FoundationTrialBatch,
    FoundationTrialBatchResult,
    evaluate_foundation,
    evaluate_foundation_lengths,
    evaluate_foundation_lengths_batch,
    evaluate_foundation_sdf,
    fit_foundation_material_autodiff,
    fit_foundation_material_batches_autodiff,
    foundation_lengths_batch_loss_gradient,
    foundation_lengths_loss_gradient,
)
from .frame_qc import FrameConfig, FrameQCError, infer_frame_config, load_trial_frame
from .cycle_windows import CycleWindowTrace, build_cycle_window_trace, infer_cycle_column, write_cycle_window_trace
from .geometry import (
    CylinderGrid,
    MeshFrame,
    MeshQCError,
    PlacedCylinderGrid,
    SpringSurfaceGrid,
    build_raycast_spring_grid,
    condition_midsole_mesh,
    detect_mesh_frame,
    make_cylinder_grid,
    make_footprint_grid,
    place_rearfoot_punch_grid,
    raycast_grid_thickness,
    rearfoot_punch_center_uv,
)
from .manifest import Trial, TrialManifest, load_manifest, validate_frame_config
from .validation import (
    TraceValidationMetrics,
    active_force_mask,
    baseline_correct_force,
    positive_hysteresis_work,
    robust_peak,
    validate_trace_metrics,
)
from .visualization import write_visualization_report

__all__ = [
    "CylinderGrid",
    "CycleWindowTrace",
    "FoundationFitResult",
    "FoundationFitSample",
    "FoundationGradientResult",
    "FoundationMaterial",
    "FoundationResult",
    "FoundationTrialBatch",
    "FoundationTrialBatchResult",
    "FrameConfig",
    "FrameQCError",
    "MeshFrame",
    "MeshQCError",
    "PlacedCylinderGrid",
    "SpringSurfaceGrid",
    "Trial",
    "TrialManifest",
    "TraceValidationMetrics",
    "active_force_mask",
    "baseline_correct_force",
    "build_cycle_window_trace",
    "build_raycast_spring_grid",
    "condition_midsole_mesh",
    "detect_mesh_frame",
    "evaluate_foundation",
    "evaluate_foundation_lengths",
    "evaluate_foundation_lengths_batch",
    "evaluate_foundation_sdf",
    "fit_foundation_material_autodiff",
    "fit_foundation_material_batches_autodiff",
    "foundation_lengths_batch_loss_gradient",
    "foundation_lengths_loss_gradient",
    "infer_frame_config",
    "infer_cycle_column",
    "load_manifest",
    "load_trial_frame",
    "make_cylinder_grid",
    "make_footprint_grid",
    "place_rearfoot_punch_grid",
    "raycast_grid_thickness",
    "rearfoot_punch_center_uv",
    "positive_hysteresis_work",
    "robust_peak",
    "validate_frame_config",
    "validate_trace_metrics",
    "write_cycle_window_trace",
    "write_visualization_report",
]
