from dataclasses import dataclass
from typing import ClassVar


@dataclass
class Go2:
    num_dofs: ClassVar[int] = 12
    policy_path: ClassVar[dict[str, str]] = {"mjw": "./assets/mjw_go2.pt", "physx": "./assets/physx_go2.pt"}
    asset_path: ClassVar[str] = "go2.usd"
    action_scale: ClassVar[float] = 0.25
    mjw_joint_names: ClassVar[list[str]] = [
        "FL_hip_joint",
        "FL_thigh_joint",
        "FL_calf_joint",
        "FR_hip_joint",
        "FR_thigh_joint",
        "FR_calf_joint",
        "RL_hip_joint",
        "RL_thigh_joint",
        "RL_calf_joint",
        "RR_hip_joint",
        "RR_thigh_joint",
        "RR_calf_joint",
    ]
    physx_joint_names: ClassVar[list[str]] = [
        "FL_hip_joint",
        "FR_hip_joint",
        "RL_hip_joint",
        "RR_hip_joint",
        "FL_thigh_joint",
        "FR_thigh_joint",
        "RL_thigh_joint",
        "RR_thigh_joint",
        "FL_calf_joint",
        "FR_calf_joint",
        "RL_calf_joint",
        "RR_calf_joint",
    ]

    mjw_joint_pos: ClassVar[list[float]] = [
        0.1000,
        0.8000,
        -1.5000,
        -0.1000,
        0.8000,
        -1.5000,
        0.1000,
        1.0000,
        -1.5000,
        -0.1000,
        1.0000,
        -1.5000,
    ]
    mjw_joint_stiffness: ClassVar[list[float]] = [50.0] * num_dofs
    mjw_joint_damping: ClassVar[list[float]] = [1.0] * num_dofs
    mjw_joint_armature: ClassVar[list[float]] = [0.1] * num_dofs


@dataclass
class Anymal:
    num_dofs: ClassVar[int] = 12
    policy_path: ClassVar[dict[str, str]] = {"mjw": "./assets/mjw_anymal.pt", "physx": "./assets/physx_anymal.pt"}
    asset_path: ClassVar[str] = "anymal_c.usd"
    action_scale: ClassVar[float] = 0.5
    mjw_joint_names: ClassVar[list[str]] = [
        "LF_HAA",
        "LF_HFE",
        "LF_KFE",
        "LH_HAA",
        "LH_HFE",
        "LH_KFE",
        "RF_HAA",
        "RF_HFE",
        "RF_KFE",
        "RH_HAA",
        "RH_HFE",
        "RH_KFE",
    ]
    physx_joint_names: ClassVar[list[str]] = [
        "LF_HAA",
        "LH_HAA",
        "RF_HAA",
        "RH_HAA",
        "LF_HFE",
        "LH_HFE",
        "RF_HFE",
        "RH_HFE",
        "LF_KFE",
        "LH_KFE",
        "RF_KFE",
        "RH_KFE",
    ]
    mjw_joint_pos: ClassVar[list[float]] = [
        0.0000,
        0.4000,
        -0.8000,
        0.0000,
        -0.4000,
        0.8000,
        0.0000,
        0.4000,
        -0.8000,
        0.0000,
        -0.4000,
        0.8000,
    ]

    mjw_joint_stiffness: ClassVar[list[float]] = [300.0] * num_dofs
    mjw_joint_damping: ClassVar[list[float]] = [10.0] * num_dofs
    mjw_joint_armature: ClassVar[list[float]] = [0.06] * num_dofs


@dataclass
class G1_23DOF:
    num_dofs: ClassVar[int] = 37
    policy_path: ClassVar[dict[str, str]] = {"mjw": "./assets/mjw_g1_23DOF.pt", "physx": "./assets/physx_g1.pt"}
    asset_path: ClassVar[str] = "g1_minimal.usd"
    action_scale: ClassVar[float] = 0.5
    mjw_joint_names: ClassVar[list[str]] = [
        "left_hip_pitch_joint",
        "left_hip_roll_joint",
        "left_hip_yaw_joint",
        "left_knee_joint",
        "left_ankle_pitch_joint",
        "left_ankle_roll_joint",
        "right_hip_pitch_joint",
        "right_hip_roll_joint",
        "right_hip_yaw_joint",
        "right_knee_joint",
        "right_ankle_pitch_joint",
        "right_ankle_roll_joint",
        "torso_joint",
        "left_shoulder_pitch_joint",
        "left_shoulder_roll_joint",
        "left_shoulder_yaw_joint",
        "left_elbow_pitch_joint",
        "left_elbow_roll_joint",
        "left_five_joint",
        "left_six_joint",
        "left_three_joint",
        "left_four_joint",
        "left_zero_joint",
        "left_one_joint",
        "left_two_joint",
        "right_shoulder_pitch_joint",
        "right_shoulder_roll_joint",
        "right_shoulder_yaw_joint",
        "right_elbow_pitch_joint",
        "right_elbow_roll_joint",
        "right_five_joint",
        "right_six_joint",
        "right_three_joint",
        "right_four_joint",
        "right_zero_joint",
        "right_one_joint",
        "right_two_joint",
    ]
    physx_joint_names: ClassVar[list[str]] = [
        "left_hip_pitch_joint",
        "right_hip_pitch_joint",
        "torso_joint",
        "left_hip_roll_joint",
        "right_hip_roll_joint",
        "left_shoulder_pitch_joint",
        "right_shoulder_pitch_joint",
        "left_hip_yaw_joint",
        "right_hip_yaw_joint",
        "left_shoulder_roll_joint",
        "right_shoulder_roll_joint",
        "left_knee_joint",
        "right_knee_joint",
        "left_shoulder_yaw_joint",
        "right_shoulder_yaw_joint",
        "left_ankle_pitch_joint",
        "right_ankle_pitch_joint",
        "left_elbow_pitch_joint",
        "right_elbow_pitch_joint",
        "left_ankle_roll_joint",
        "right_ankle_roll_joint",
        "left_elbow_roll_joint",
        "right_elbow_roll_joint",
        "left_five_joint",
        "left_three_joint",
        "left_zero_joint",
        "right_five_joint",
        "right_three_joint",
        "right_zero_joint",
        "left_six_joint",
        "left_four_joint",
        "left_one_joint",
        "right_six_joint",
        "right_four_joint",
        "right_one_joint",
        "left_two_joint",
        "right_two_joint",
    ]
    mjw_joint_pos: ClassVar[list[float]] = [
        -0.2,
        0.0,
        0.0,
        0.42,
        -0.23,
        0.0,
        -0.2,
        0.0,
        0.0,
        0.42,
        -0.23,
        0.0,
        0.0,
        0.35,
        0.16,
        0.0,
        0.87,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.52,
        0.35,
        -0.16,
        0.0,
        0.87,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        -1.0,
        -0.52,
    ]
    mjw_joint_stiffness: ClassVar[list[float]] = [
        200.0,
        150.0,
        150.0,
        200.0,
        20.0,
        20.0,
        200.0,
        150.0,
        150.0,
        200.0,
        20.0,
        20.0,
        200.0,
        40.0,
        40.0,
        40.0,
        40.0,
        40.0,
        40.0,
        40.0,
        40.0,
        40.0,
        40.0,
        40.0,
        40.0,
        40.0,
        40.0,
        40.0,
        40.0,
        40.0,
        40.0,
        40.0,
        40.0,
        40.0,
        40.0,
        40.0,
        40.0,
    ]
    mjw_joint_damping: ClassVar[list[float]] = [
        5.0,
        5.0,
        5.0,
        5.0,
        2.0,
        2.0,
        5.0,
        5.0,
        5.0,
        5.0,
        2.0,
        2.0,
        5.0,
        10.0,
        10.0,
        10.0,
        10.0,
        10.0,
        10.0,
        10.0,
        10.0,
        10.0,
        10.0,
        10.0,
        10.0,
        10.0,
        10.0,
        10.0,
        10.0,
        10.0,
        10.0,
        10.0,
        10.0,
        10.0,
        10.0,
        10.0,
        10.0,
    ]
    mjw_joint_armature: ClassVar[list[float]] = [0.1] * num_dofs


@dataclass
class G1_29DOF:
    num_dofs: ClassVar[int] = 43
    policy_path: ClassVar[dict[str, str]] = {
        "mjw": "./assets/mjw_g1_29DOF.pt",
    }
    asset_path: ClassVar[str] = "g1_isaac.usd"
    action_scale: ClassVar[float] = 0.5
    mjw_joint_names: ClassVar[list[str]] = [
        "left_hip_pitch_joint",
        "left_hip_roll_joint",
        "left_hip_yaw_joint",
        "left_knee_joint",
        "left_ankle_pitch_joint",
        "left_ankle_roll_joint",
        "right_hip_pitch_joint",
        "right_hip_roll_joint",
        "right_hip_yaw_joint",
        "right_knee_joint",
        "right_ankle_pitch_joint",
        "right_ankle_roll_joint",
        "waist_yaw_joint",
        "waist_roll_joint",
        "waist_pitch_joint",
        "left_shoulder_pitch_joint",
        "left_shoulder_roll_joint",
        "left_shoulder_yaw_joint",
        "left_elbow_joint",
        "left_wrist_roll_joint",
        "left_wrist_pitch_joint",
        "left_wrist_yaw_joint",
        "left_hand_index_0_joint",
        "left_hand_index_1_joint",
        "left_hand_middle_0_joint",
        "left_hand_middle_1_joint",
        "left_hand_thumb_0_joint",
        "left_hand_thumb_1_joint",
        "left_hand_thumb_2_joint",
        "right_shoulder_pitch_joint",
        "right_shoulder_roll_joint",
        "right_shoulder_yaw_joint",
        "right_elbow_joint",
        "right_wrist_roll_joint",
        "right_wrist_pitch_joint",
        "right_wrist_yaw_joint",
        "right_hand_index_0_joint",
        "right_hand_index_1_joint",
        "right_hand_middle_0_joint",
        "right_hand_middle_1_joint",
        "right_hand_thumb_0_joint",
        "right_hand_thumb_1_joint",
        "right_hand_thumb_2_joint",
    ]
    mjw_joint_pos: ClassVar[list[float]] = [
        -0.1,
        0.0,
        0.0,
        0.3,
        -0.2,
        0.0,
        -0.1,
        0.0,
        0.0,
        0.3,
        -0.2,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
    ]
    mjw_joint_stiffness: ClassVar[list[float]] = [
        200.0,
        150.0,
        150.0,
        200.0,
        20.0,
        20.0,
        200.0,
        150.0,
        150.0,
        200.0,
        20.0,
        20.0,
        300.0,
        300.0,
        300.0,
        40.0,
        40.0,
        40.0,
        40.0,
        20.0,
        20.0,
        20.0,
        10.0,
        10.0,
        10.0,
        10.0,
        10.0,
        10.0,
        10.0,
        40.0,
        40.0,
        40.0,
        40.0,
        20.0,
        20.0,
        20.0,
        10.0,
        10.0,
        10.0,
        10.0,
        10.0,
        10.0,
        10.0,
    ]
    mjw_joint_damping: ClassVar[list[float]] = [
        5.0,
        5.0,
        5.0,
        5.0,
        2.0,
        2.0,
        5.0,
        5.0,
        5.0,
        5.0,
        2.0,
        2.0,
        5.0,
        5.0,
        5.0,
        10.0,
        10.0,
        10.0,
        10.0,
        0.5,
        0.5,
        0.5,
        2.0,
        2.0,
        2.0,
        2.0,
        2.0,
        2.0,
        2.0,
        10.0,
        10.0,
        10.0,
        10.0,
        0.5,
        0.5,
        0.5,
        2.0,
        2.0,
        2.0,
        2.0,
        2.0,
        2.0,
        2.0,
    ]
    mjw_joint_armature: ClassVar[list[float]] = [0.1] * num_dofs
