# SPDX-FileCopyrightText: Copyright (c) 2026 The Newton Developers
# SPDX-License-Identifier: Apache-2.0

"""Causal, variable-impedance runner dynamics without measured reference inputs.

This is an effective joint-actuation model, not a muscle identification claim.
An internal oscillator and simulated sensory state generate bounded equilibrium,
stiffness, and damping. Only relative hip/knee/ankle coordinates are actuated.
The existing planar chain and massless shoe remain modeling limitations.
"""

from __future__ import annotations

import json
import math
from dataclasses import asdict, dataclass, field
from pathlib import Path

import numpy as np

from .mechanics import Chain

SCHEMA = "generative_runner_2"
FEATURE_NAMES = (
    "bias",
    "sin_phase",
    "cos_phase",
    "sin_2phase",
    "cos_2phase",
    "sin_3phase",
    "cos_3phase",
    "filtered_normal_load_bw",
    "load_sin_phase",
    "load_cos_phase",
    "hip_over_ankle_leg_lengths",
    "pelvis_lean_rad",
    "speed_error",
    "task_speed_offset",
)
_SCHEMA_1_FEATURES = (
    "bias",
    "sin_phase",
    "cos_phase",
    "filtered_normal_load_bw",
    "hip_over_ankle_leg_lengths",
    "pelvis_lean_rad",
    "speed_error",
    "task_speed_offset",
)
OUTPUT_NAMES = ("equilibrium", "stiffness", "damping")


def _vector(value, size: int, name: str) -> np.ndarray:
    result = np.asarray(value, dtype=float)
    if result.shape != (size,) or not np.isfinite(result).all():
        raise ValueError(f"{name} must be finite with shape ({size},)")
    return result.copy()


@dataclass(frozen=True)
class Task:
    """Known experimental/task inputs, independent of future observations."""

    speed_m_s: float
    """Intended forward speed [m/s], not estimated from future motion."""

    def __post_init__(self):
        if not np.isfinite(self.speed_m_s) or self.speed_m_s < 0:
            raise ValueError("Task speed must be finite and nonnegative")


@dataclass(frozen=True)
class Bounds:
    """Declared engineering bounds; these are not validated physiological limits."""

    equilibrium_lower_rad: tuple[float, float, float] = (-1.5, -2.8, -1.2)
    """Hip, knee, ankle equilibrium lower bounds [rad]."""
    equilibrium_upper_rad: tuple[float, float, float] = (1.5, -0.02, 1.2)
    """Hip, knee, ankle equilibrium upper bounds [rad]."""
    stiffness_max_nm_rad: tuple[float, float, float] = (1500.0, 1500.0, 1000.0)
    """Maximum stiffness [N m/rad]."""
    damping_max_nms_rad: tuple[float, float, float] = (80.0, 80.0, 50.0)
    """Maximum damping [N m s/rad]."""
    torque_max_nm: tuple[float, float, float] = (250.0, 300.0, 200.0)
    """Maximum absolute joint torque [N m]."""
    torque_rate_max_nm_s: tuple[float, float, float] = (5000.0, 6000.0, 4000.0)
    """Maximum absolute joint torque slew rate [N m/s]."""

    def __post_init__(self):
        for name, value in asdict(self).items():
            array = _vector(value, 3, name)
            object.__setattr__(self, name, tuple(array.tolist()))
            if "max" in name and np.any(array <= 0):
                raise ValueError(f"{name} must be positive")
        if np.any(np.asarray(self.equilibrium_lower_rad) >= self.equilibrium_upper_rad):
            raise ValueError("Equilibrium lower bounds must be below upper bounds")


@dataclass
class State:
    """Physical and internal runner state, never a reference-trajectory sample."""

    q: np.ndarray
    """[hip x, hip z, pelvis, hip, knee, ankle] [m, m, rad, rad, rad, rad]."""
    v: np.ndarray
    """Coordinate velocities [m/s, m/s, rad/s, rad/s, rad/s, rad/s]."""
    phase_rad: float = 0.0
    """Internal oscillator phase [rad]."""
    normal_load_bw: float = 0.0
    """Filtered simulated normal load divided by body weight."""
    torque_nm: np.ndarray = field(default_factory=lambda: np.zeros(3))
    """Activation-filtered hip, knee, ankle torques [N m]."""

    def __post_init__(self):
        self.q = _vector(self.q, 6, "q")
        self.v = _vector(self.v, 6, "v")
        self.torque_nm = _vector(self.torque_nm, 3, "torque_nm")
        if not np.isfinite([self.phase_rad, self.normal_load_bw]).all() or self.normal_load_bw < 0:
            raise ValueError("Internal state must be finite with nonnegative normal load")

    def copy(self) -> State:
        """Copy the complete runner state without sharing mutable arrays."""
        return State(self.q, self.v, self.phase_rad, self.normal_load_bw, self.torque_nm)


class Runner:
    """Shared state-conditioned equilibrium, stiffness, and damping model.

    The command is ``K * (equilibrium - q_joint) - D * v_joint``. There is no
    reference velocity or inverse-dynamics feedforward. Equilibrium motion is
    active behavior generated by the internal model; this is not a passive law.
    A first-order torque response and slew bound approximate finite actuation
    bandwidth, not a validated muscle activation or reflex-delay model. An
    optional intrinsic damping ``-c * v_joint`` bypasses that lag, standing in
    for passive muscle and tissue viscosity.

    Args:
        weights: Feature weights, shape [3 outputs, 3 joints, 14 features].
        bounds: Fixed engineering bounds recorded with the model.
        frequency_hz: Autonomous stride frequency [Hz].
        response_time_s: Joint torque response time [s].
        reference_speed_m_s: Training speed origin for task conditioning [m/s].
        speed_scale_m_s: Fixed feature normalization [m/s].
        cadence_speed_gain: Log-frequency change per normalized task speed.
        load_time_s: Normal-load sensory filter time [s].
        phase_feedback: Fractional bounded oscillator-rate modulation by load.
        intrinsic_damping_nms_rad: Hip, knee, ankle damping applied without the
            torque response lag [N m s/rad]; the total torque keeps the cap.
    """

    def __init__(
        self,
        weights,
        *,
        bounds: Bounds | None = None,
        frequency_hz: float = 1.5,
        response_time_s: float = 0.025,
        reference_speed_m_s: float = 3.7,
        speed_scale_m_s: float = 1.0,
        cadence_speed_gain: float = 0.0,
        load_time_s: float = 0.02,
        phase_feedback: float = 0.2,
        intrinsic_damping_nms_rad=(0.0, 0.0, 0.0),
    ):
        self.weights = np.array(weights, dtype=float, copy=True)
        if self.weights.shape != (3, 3, len(FEATURE_NAMES)) or not np.isfinite(self.weights).all():
            raise ValueError(f"weights must be finite with shape (3, 3, {len(FEATURE_NAMES)})")
        self.weights.setflags(write=False)
        self.bounds = bounds or Bounds()
        values = (
            frequency_hz,
            response_time_s,
            reference_speed_m_s,
            speed_scale_m_s,
            cadence_speed_gain,
            load_time_s,
            phase_feedback,
        )
        if not np.isfinite(values).all():
            raise ValueError("Runner parameters must be finite")
        if min(frequency_hz, response_time_s, speed_scale_m_s, load_time_s) <= 0:
            raise ValueError("Frequency, time constants, and speed scale must be positive")
        if reference_speed_m_s < 0 or not 0 <= phase_feedback < 1:
            raise ValueError("Reference speed must be nonnegative and phase feedback in [0, 1)")
        self.frequency_hz = float(frequency_hz)
        self.response_time_s = float(response_time_s)
        self.reference_speed_m_s = float(reference_speed_m_s)
        self.speed_scale_m_s = float(speed_scale_m_s)
        self.cadence_speed_gain = float(cadence_speed_gain)
        self.load_time_s = float(load_time_s)
        self.phase_feedback = float(phase_feedback)
        self.intrinsic_damping_nms_rad = _vector(intrinsic_damping_nms_rad, 3, "intrinsic_damping_nms_rad")
        if np.any(self.intrinsic_damping_nms_rad < 0):
            raise ValueError("intrinsic_damping_nms_rad must be nonnegative")
        self.intrinsic_damping_nms_rad.setflags(write=False)

    @classmethod
    def seed(cls, *, reference_speed_m_s: float = 3.7) -> Runner:
        """Construct an unfitted engineering seed without reading measured motion."""
        bounds = Bounds()
        lower = np.asarray(bounds.equilibrium_lower_rad)
        span = np.asarray(bounds.equilibrium_upper_rad) - lower
        fractions = np.array(
            [
                (np.array([0.2, -0.5, 0.0]) - lower) / span,
                np.array([250.0, 300.0, 200.0]) / bounds.stiffness_max_nm_rad,
                np.array([12.0, 10.0, 6.0]) / bounds.damping_max_nms_rad,
            ]
        )
        weights = np.zeros((3, 3, len(FEATURE_NAMES)))
        weights[:, :, 0] = np.log(fractions / (1 - fractions))
        weights[0, :, FEATURE_NAMES.index("sin_phase")] = [0.35, -0.4, -0.2]
        weights[1, :, FEATURE_NAMES.index("filtered_normal_load_bw")] = [0.1, 0.2, 0.2]
        return cls(weights, bounds=bounds, reference_speed_m_s=reference_speed_m_s)

    def features(self, state: State, chain: Chain, task: Task) -> np.ndarray:
        """Return bounded sensory features using only current/internal state."""
        ankle = chain.point(state.q, 3, np.zeros(2))[0]
        phase = state.phase_rad
        load = np.clip(state.normal_load_bw, 0.0, 4.0)
        return np.array(
            [
                1.0,
                math.sin(phase),
                math.cos(phase),
                math.sin(2 * phase),
                math.cos(2 * phase),
                math.sin(3 * phase),
                math.cos(3 * phase),
                load,
                load * math.sin(phase),
                load * math.cos(phase),
                np.clip((state.q[0] - ankle[0]) / np.sum(chain.lengths_m), -1.0, 1.0),
                np.clip(state.q[2] - math.pi / 2, -1.0, 1.0),
                np.clip((task.speed_m_s - state.v[0]) / self.speed_scale_m_s, -2.0, 2.0),
                np.clip((task.speed_m_s - self.reference_speed_m_s) / self.speed_scale_m_s, -2.0, 2.0),
            ]
        )

    def impedance(self, state: State, chain: Chain, task: Task) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
        """Return equilibrium [rad], stiffness [N m/rad], damping [N m s/rad]."""
        logits = np.clip(self.weights @ self.features(state, chain, task), -40.0, 40.0)
        fraction = 1.0 / (1.0 + np.exp(-logits))
        low = np.asarray(self.bounds.equilibrium_lower_rad)
        equilibrium = low + (np.asarray(self.bounds.equilibrium_upper_rad) - low) * fraction[0]
        return (
            equilibrium,
            np.asarray(self.bounds.stiffness_max_nm_rad) * fraction[1],
            np.asarray(self.bounds.damping_max_nms_rad) * fraction[2],
        )

    def actuate(self, state: State, chain: Chain, task: Task, dt_s: float) -> tuple[np.ndarray, dict]:
        """Advance joint torque activation and return a six-coordinate load.

        Modifies only ``state.torque_nm``. Floating-base channels remain exactly
        zero, including pelvis angle. The sensed load is from the preceding step.
        """
        if not np.isfinite(dt_s) or dt_s <= 0:
            raise ValueError("dt_s must be finite and positive")
        cap = np.asarray(self.bounds.torque_max_nm)
        if np.any(np.abs(state.torque_nm) > cap):
            raise ValueError("Initial torque exceeds the model bounds")
        equilibrium, stiffness, damping = self.impedance(state, chain, task)
        raw = stiffness * (equilibrium - state.q[3:]) - damping * state.v[3:]
        desired = np.clip(raw, -cap, cap)
        fraction = -math.expm1(-dt_s / self.response_time_s)
        rate = np.asarray(self.bounds.torque_rate_max_nm_s) * dt_s
        change = np.clip(fraction * (desired - state.torque_nm), -rate, rate)
        state.torque_nm = np.clip(state.torque_nm + change, -cap, cap)
        load = np.zeros(6)
        load[3:] = np.clip(state.torque_nm - self.intrinsic_damping_nms_rad * state.v[3:], -cap, cap)
        return load, {
            "equilibrium_rad": equilibrium,
            "stiffness_nm_rad": stiffness,
            "damping_nms_rad": damping,
            "torque_saturated": np.abs(raw) > cap,
        }

    def advance_sensors(self, state: State, normal_force_n: float, body_weight_n: float, task: Task, dt_s: float):
        """Advance load memory and continuous oscillator using simulated contact."""
        if not np.isfinite([normal_force_n, body_weight_n, dt_s]).all() or min(body_weight_n, dt_s) <= 0:
            raise ValueError("Sensory inputs must be finite with positive body weight and timestep")
        load = max(normal_force_n, 0.0) / body_weight_n
        state.normal_load_bw += -math.expm1(-dt_s / self.load_time_s) * (load - state.normal_load_bw)
        speed = np.clip((task.speed_m_s - self.reference_speed_m_s) / self.speed_scale_m_s, -2.0, 2.0)
        frequency = self.frequency_hz * math.exp(float(np.clip(self.cadence_speed_gain * speed, -2.0, 2.0)))
        modulation = 1.0 - self.phase_feedback * min(state.normal_load_bw, 1.0) * math.sin(state.phase_rad)
        state.phase_rad = (state.phase_rad + 2 * math.pi * frequency * modulation * dt_s) % (2 * math.pi)

    def to_dict(self) -> dict:
        """Serialize all model parameters without per-stance targets or state."""
        return {
            "schema": SCHEMA,
            "features": list(FEATURE_NAMES),
            "outputs": list(OUTPUT_NAMES),
            "weights": self.weights.tolist(),
            "bounds": asdict(self.bounds),
            **{
                name: getattr(self, name)
                for name in (
                    "frequency_hz",
                    "response_time_s",
                    "reference_speed_m_s",
                    "speed_scale_m_s",
                    "cadence_speed_gain",
                    "load_time_s",
                    "phase_feedback",
                )
            },
            "intrinsic_damping_nms_rad": self.intrinsic_damping_nms_rad.tolist(),
        }

    @classmethod
    def from_dict(cls, data: dict) -> Runner:
        """Load a versioned model, rejecting incompatible feature semantics.

        Schema-1 models load exactly: their features are a subset, so the added
        harmonic and load-phase weights are zero.
        """
        data = dict(data)
        schema, features = data.pop("schema"), data.pop("features")
        if schema == "generative_runner_1" and features == list(_SCHEMA_1_FEATURES):
            old = np.asarray(data["weights"], dtype=float)
            if old.shape != (3, 3, len(_SCHEMA_1_FEATURES)):
                raise ValueError("Schema-1 weights must have shape (3, 3, 8)")
            weights = np.zeros((3, 3, len(FEATURE_NAMES)))
            weights[:, :, [FEATURE_NAMES.index(name) for name in _SCHEMA_1_FEATURES]] = old
            data["weights"] = weights
        elif schema != SCHEMA or features != list(FEATURE_NAMES):
            raise ValueError("Unsupported runner schema or features")
        if data.pop("outputs") != list(OUTPUT_NAMES):
            raise ValueError("Unsupported runner outputs")
        data["bounds"] = Bounds(**data["bounds"])
        return cls(**data)

    def save(self, path: str | Path) -> None:
        """Write a portable JSON model with finite values only."""
        Path(path).write_text(json.dumps(self.to_dict(), indent=2, allow_nan=False) + "\n", encoding="utf-8")

    @classmethod
    def load(cls, path: str | Path) -> Runner:
        """Read a portable JSON model."""
        return cls.from_dict(json.loads(Path(path).read_text(encoding="utf-8")))


@dataclass(frozen=True)
class RolloutConfig:
    """Numerical screens, explicitly separate from physical validation."""

    dt_s: float = 1.25e-4
    """Maximum integration timestep [s]."""
    gravity_m_s2: float = 9.81
    """Gravity magnitude [m/s^2]; positive also defines body-weight normalization."""
    maximum_force_n: float = 6000.0
    """Contact force numerical screen [N]."""
    minimum_hip_height_m: float = 0.2
    """Minimum hip height [m]."""
    maximum_speed: float = 100.0
    """Numerical speed bound, separately applied to translation [m/s] and angles [rad/s]."""
    compression_limit: float = 0.9
    """Maximum driven-column compression divided by rest thickness."""
    contact_threshold_n: float = 50.0
    """Normal-force threshold for contact diagnostics [N]."""

    def __post_init__(self):
        values = asdict(self)
        if not np.isfinite(list(values.values())).all():
            raise ValueError("Rollout settings must be finite")
        positive = (self.dt_s, self.gravity_m_s2, self.maximum_force_n, self.maximum_speed, self.contact_threshold_n)
        if min(positive) <= 0 or not 0 < self.compression_limit < 1:
            raise ValueError("Timestep, gravity, force, speed, threshold must be positive; compression in (0, 1)")


def simulate(
    runner: Runner,
    chain: Chain,
    shoe,
    initial: State,
    task: Task,
    *,
    duration_s: float,
    config: RolloutConfig | None = None,
) -> tuple[dict[str, np.ndarray], dict]:
    """Generate a free rollout using initial state, task, body, and shoe only.

    Each call starts with a relaxed shoe; it is an independent single-leg window,
    not a restart/checkpoint API for continuous running. The input runner state
    is copied. Time/state arrays include the terminal sample; force and actuation
    arrays describe the intervals starting at ``time_s[:-1]``. No target arrays,
    measured events, inverse dynamics, or tracking-plan objects are accepted.
    """
    cfg = config or RolloutConfig()
    if not np.isfinite(duration_s) or duration_s <= 0:
        raise ValueError("duration_s must be finite and positive")
    steps = math.ceil(duration_s / cfg.dt_s)
    dt = duration_s / steps
    state = initial.copy()
    if np.any(np.abs(state.torque_nm) > runner.bounds.torque_max_nm):
        raise ValueError("Initial torque exceeds the model bounds")
    shoe.foundation.reset()
    driven = shoe.foundation.driven.numpy().astype(bool)
    rest = np.asarray(shoe.shoe.column_bed.rest_length_m)[driven]
    foot_angular = chain.angular_jacobian(3)
    states, velocities, phases, loads_bw = [state.q.copy()], [state.v.copy()], [state.phase_rad], [state.normal_load_bw]
    records = {
        key: []
        for key in (
            "load",
            "grf_n",
            "ankle_contact_moment_nm",
            "compression_fraction",
            "equilibrium_rad",
            "stiffness_nm_rad",
            "damping_nms_rad",
            "torque_saturated",
        )
    }
    failure = None
    try:
        for _ in range(steps):
            if state.q[1] < cfg.minimum_hip_height_m:
                failure = "Hip height screen exceeded"
                break
            if np.linalg.norm(state.v[:2]) > cfg.maximum_speed or np.max(np.abs(state.v[2:])) > cfg.maximum_speed:
                failure = "Numerical speed screen exceeded"
                break
            load, info = runner.actuate(state, chain, task, dt)
            ankle, jacobian, _ = chain.point(state.q, 3, np.zeros(2))
            wrench, _ = shoe.apply(
                ankle, jacobian @ state.v, chain.angle(state.q, 3), float(foot_angular @ state.v), dt
            )
            wrench = np.asarray(wrench, dtype=float)
            compression = float(np.max(shoe.foundation.compression.numpy()[driven] / rest))
            if not np.isfinite(wrench).all() or not np.isfinite(compression) or not np.isfinite(load).all():
                failure = "Nonfinite actuator/contact output"
                break
            if wrench[1] < -1e-6 or np.linalg.norm(wrench[:2]) > cfg.maximum_force_n:
                failure = "Contact force screen exceeded"
                break
            if compression > cfg.compression_limit + 1e-6:
                failure = "Driven shoe compression screen exceeded"
                break
            mass, bias = chain.dynamics(state.q, state.v, cfg.gravity_m_s2)
            force = load + jacobian.T @ wrench[:2] + foot_angular * wrench[2]
            try:
                acceleration = np.linalg.solve(mass, force - bias)
            except np.linalg.LinAlgError:
                failure = "Singular mass matrix"
                break
            velocity = state.v + dt * acceleration
            position = state.q + dt * velocity
            if not np.isfinite(position).all() or not np.isfinite(velocity).all():
                failure = "Nonfinite integrated state"
                break
            if position[1] < cfg.minimum_hip_height_m or (
                np.linalg.norm(velocity[:2]) > cfg.maximum_speed or np.max(np.abs(velocity[2:])) > cfg.maximum_speed
            ):
                failure = "Integrated state exceeded height/speed screen"
                break
            for name, value in {
                **info,
                "load": load,
                "grf_n": wrench[:2],
                "ankle_contact_moment_nm": wrench[2],
                "compression_fraction": compression,
            }.items():
                records[name].append(np.array(value, copy=True))
            runner.advance_sensors(state, float(wrench[1]), chain.total_mass_kg * cfg.gravity_m_s2, task, dt)
            state.q, state.v = position, velocity
            states.append(position.copy())
            velocities.append(velocity.copy())
            phases.append(state.phase_rad)
            loads_bw.append(state.normal_load_bw)
    finally:
        shoe.foundation.reset()
    count = len(states) - 1
    trace = {key: np.asarray(value) for key, value in records.items()}
    for key, width in (
        ("load", 6),
        ("grf_n", 2),
        ("equilibrium_rad", 3),
        ("stiffness_nm_rad", 3),
        ("damping_nms_rad", 3),
        ("torque_saturated", 3),
    ):
        trace[key] = trace[key].reshape(count, width)
    trace.update(
        time_s=np.arange(count + 1) * dt,
        state=np.asarray(states),
        velocity=np.asarray(velocities),
        phase_rad=np.asarray(phases),
        normal_load_bw=np.asarray(loads_bw),
    )
    power = trace["load"][:, 3:] * trace["velocity"][:-1, 3:]
    contact = trace["grf_n"][:, 1] > cfg.contact_threshold_n
    indices = np.flatnonzero(contact)
    summary = {
        "status": "completed" if failure is None else "failed",
        "failure": failure,
        "failure_time_s": None if failure is None else count * dt,
        "dt_s": dt,
        "contact_threshold_n": cfg.contact_threshold_n,
        "requested_duration_s": duration_s,
        "integrated_duration_s": count * dt,
        "reference_inputs_used": False,
        "external_actuator_load": [0.0, 0.0, 0.0],
        "peak_grf_n": trace["grf_n"].max(0).tolist() if count else [0.0, 0.0],
        "grf_impulse_ns": (trace["grf_n"].sum(0) * dt).tolist(),
        "contact_duration_s": float(np.count_nonzero(contact) * dt),
        "touchdown_s": float(indices[0] * dt) if len(indices) else None,
        "toeoff_s": float((indices[-1] + 1) * dt) if len(indices) else None,
        "joint_positive_work_j": (np.maximum(power, 0).sum(0) * dt).tolist(),
        "joint_negative_work_j": (np.minimum(power, 0).sum(0) * dt).tolist(),
        "torque_saturation_fraction": trace["torque_saturated"].mean(0).tolist() if count else [0.0] * 3,
        "terminal_state": state.q.tolist(),
        "terminal_velocity": state.v.tolist(),
        "validated": False,
    }
    return trace, summary
